---
- name: Setup Webserver
  hosts: web_server_grp
  become: yes
  tasks:
    - name: Install Apache2 server
      apt:
        name: apache2
        state: present
    - name: Start Httpd server
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Deploy web file
      copy:
        src: index.html
        dest: /var/www/html/index.html

- name: Setup DBserver
  hosts: db_server_grp
  become: yes
  tasks:

    - name: Install MySQL server
      shell: apt-get -y install mysql-server

    - name: Install MySQL client
      shell: apt-get -y install mysql-client    

    - name: Start and enable server
      service:
        name: mysql
        state: started
        enabled: yes
